### ISSUE TITLE
Meta: Flix

### ISSUE THREAD

**Issue by sirinath** [plast-lab/cclyzer#7]
#Flix (http://flix.github.io/) maybe an alternative to using DataLog. Just a pointer. Also open source!

**Comment by gbalats** [comment]
I'm aware of [Flix](https://github.com/flix/flix) and it would be nice to incorporate it as an alternative Datalog Engine.

However, Flix and LB Datalog use very different dialects of Datalog with different features, so the entire logic of the analysis would have to be rewritten, which is not really an option.

Also, the [Flix web page](http://flix.github.io/doc/) states:

> NB: Flix is still under major development and the language is expected to change.

Since it's still on early development, I wouldn't expect its performance to be anywhere near LB Datalog's.

But thanks for the pointer! I'll reconsider in the future if the languages become more compatible.

**Comment by sirinath** [comment]
Maybe you can open an issue for compatibility in the Flix issue tracker.
